"""Static demo data used to stub API responses."""
from datetime import datetime, timedelta
from typing import Any, Dict, List


now = datetime.utcnow()

travels: List[Dict[str, Any]] = [
    # Yaounde to Douala routes
    {
        "id": "route-yaounde-douala-morning",
        "origin": "Yaounde",
        "destination": "Douala",
        "departure_time": now.replace(hour=6, minute=0, second=0, microsecond=0),
        "estimated_arrival": now.replace(hour=9, minute=45, second=0, microsecond=0),
        "available_seats": 8,
        "price_per_seat": 5500.0,
        "confidence": 0.91,
        "distance_km": 230.0,
        "duration_minutes": 225,
        "amenities": ["AC", "WiFi", "USB Charging"],
    },
    {
        "id": "route-yaounde-douala-midday",
        "origin": "Yaounde",
        "destination": "Douala",
        "departure_time": now.replace(hour=8, minute=30, second=0, microsecond=0),
        "estimated_arrival": now.replace(hour=12, minute=0, second=0, microsecond=0),
        "available_seats": 14,
        "price_per_seat": 5000.0,
        "confidence": 0.86,
        "distance_km": 230.0,
        "duration_minutes": 210,
        "amenities": ["AC", "WiFi"],
    },
    {
        "id": "route-yaounde-douala-evening",
        "origin": "Yaounde",
        "destination": "Douala",
        "departure_time": now.replace(hour=15, minute=0, second=0, microsecond=0),
        "estimated_arrival": now.replace(hour=18, minute=30, second=0, microsecond=0),
        "available_seats": 6,
        "price_per_seat": 4800.0,
        "confidence": 0.82,
        "distance_km": 230.0,
        "duration_minutes": 210,
        "amenities": ["AC"],
    },
    # Douala to Yaounde routes
    {
        "id": "route-douala-yaounde-morning",
        "origin": "Douala",
        "destination": "Yaounde",
        "departure_time": now.replace(hour=7, minute=0, second=0, microsecond=0),
        "estimated_arrival": now.replace(hour=10, minute=45, second=0, microsecond=0),
        "available_seats": 12,
        "price_per_seat": 5000.0,
        "confidence": 0.89,
        "distance_km": 230.0,
        "duration_minutes": 225,
        "amenities": ["AC", "WiFi", "Snacks"],
    },
    {
        "id": "route-douala-yaounde-afternoon",
        "origin": "Douala",
        "destination": "Yaounde",
        "departure_time": now.replace(hour=14, minute=30, second=0, microsecond=0),
        "estimated_arrival": now.replace(hour=18, minute=15, second=0, microsecond=0),
        "available_seats": 18,
        "price_per_seat": 4900.0,
        "confidence": 0.85,
        "distance_km": 230.0,
        "duration_minutes": 225,
        "amenities": ["AC", "WiFi"],
    },
    # Douala to Buea routes
    {
        "id": "route-douala-buea-morning",
        "origin": "Douala",
        "destination": "Buea",
        "departure_time": now.replace(hour=7, minute=30, second=0, microsecond=0),
        "estimated_arrival": now.replace(hour=9, minute=0, second=0, microsecond=0),
        "available_seats": 16,
        "price_per_seat": 3800.0,
        "confidence": 0.88,
        "distance_km": 70.0,
        "duration_minutes": 90,
        "amenities": ["AC", "WiFi"],
    },
    {
        "id": "route-douala-buea-midday",
        "origin": "Douala",
        "destination": "Buea",
        "departure_time": now.replace(hour=10, minute=0, second=0, microsecond=0),
        "estimated_arrival": now.replace(hour=11, minute=30, second=0, microsecond=0),
        "available_seats": 9,
        "price_per_seat": 3500.0,
        "confidence": 0.78,
        "distance_km": 70.0,
        "duration_minutes": 90,
        "amenities": ["AC"],
    },
    {
        "id": "route-douala-buea-evening",
        "origin": "Douala",
        "destination": "Buea",
        "departure_time": now.replace(hour=16, minute=0, second=0, microsecond=0),
        "estimated_arrival": now.replace(hour=17, minute=30, second=0, microsecond=0),
        "available_seats": 11,
        "price_per_seat": 3500.0,
        "confidence": 0.80,
        "distance_km": 70.0,
        "duration_minutes": 90,
        "amenities": ["AC", "WiFi"],
    },
    # Buea to Douala routes
    {
        "id": "route-buea-douala-morning",
        "origin": "Buea",
        "destination": "Douala",
        "departure_time": now.replace(hour=6, minute=30, second=0, microsecond=0),
        "estimated_arrival": now.replace(hour=8, minute=0, second=0, microsecond=0),
        "available_seats": 13,
        "price_per_seat": 3600.0,
        "confidence": 0.87,
        "distance_km": 70.0,
        "duration_minutes": 90,
        "amenities": ["AC", "WiFi"],
    },
    {
        "id": "route-buea-douala-afternoon",
        "origin": "Buea",
        "destination": "Douala",
        "departure_time": now.replace(hour=13, minute=0, second=0, microsecond=0),
        "estimated_arrival": now.replace(hour=14, minute=30, second=0, microsecond=0),
        "available_seats": 15,
        "price_per_seat": 3500.0,
        "confidence": 0.83,
        "distance_km": 70.0,
        "duration_minutes": 90,
        "amenities": ["AC"],
    },
    # Yaounde to Buea routes
    {
        "id": "route-yaounde-buea",
        "origin": "Yaounde",
        "destination": "Buea",
        "departure_time": now.replace(hour=9, minute=0, second=0, microsecond=0),
        "estimated_arrival": now.replace(hour=13, minute=15, second=0, microsecond=0),
        "available_seats": 10,
        "price_per_seat": 6500.0,
        "confidence": 0.79,
        "distance_km": 290.0,
        "duration_minutes": 255,
        "amenities": ["AC", "WiFi"],
    },
    # Buea to Yaounde routes
    {
        "id": "route-buea-yaounde",
        "origin": "Buea",
        "destination": "Yaounde",
        "departure_time": now.replace(hour=10, minute=30, second=0, microsecond=0),
        "estimated_arrival": now.replace(hour=14, minute=45, second=0, microsecond=0),
        "available_seats": 12,
        "price_per_seat": 6500.0,
        "confidence": 0.81,
        "distance_km": 290.0,
        "duration_minutes": 255,
        "amenities": ["AC", "WiFi", "Snacks"],
    },
]

cities: List[Dict[str, Any]] = [
    {
        "id": "douala",
        "name": "Douala",
        "country": "Cameroon",
        "description": "Economic capital with vibrant markets, bustling ports, and beautiful coastline. Known for its rich trading heritage and diverse cultural attractions.",
        "population": 2000000,
    },
    {
        "id": "yaounde",
        "name": "Yaounde",
        "country": "Cameroon",
        "description": "Political capital nestled among lush hills. Home to numerous museums, government buildings, and cultural institutions showcasing Cameroon's heritage.",
        "population": 1500000,
    },
    {
        "id": "buea",
        "name": "Buea",
        "country": "Cameroon",
        "description": "Cool highland city known as the garden city. Famous for its botanical gardens, Mount Cameroon, and colonial architecture.",
        "population": 400000,
    },
]

attractions: List[Dict[str, Any]] = [
    # Douala attractions
    {
        "id": "douala-waterfront",
        "city_id": "douala",
        "name": "Douala Waterfront",
        "description": "Scenic harbor views with bustling fish markets and fresh seafood stalls. Perfect for sunset viewing and experiencing local commerce.",
        "category": "nature",
        "rating": 4.6,
        "opening_hours": "08:00-18:00",
        "entry_fee": "2000 XAF",
        "location": {"latitude": 4.052, "longitude": 9.7679, "accuracy_meters": 15},
        "tags": ["waterfront", "sunset", "seafood", "market"],
    },
    {
        "id": "douala-bonanjo",
        "city_id": "douala",
        "name": "Bonanjo Business District",
        "description": "Heart of Douala's commerce and entertainment. Features modern shopping malls, restaurants, and colonial-era buildings.",
        "category": "culture",
        "rating": 4.3,
        "opening_hours": "09:00-20:00",
        "entry_fee": "Free",
        "location": {"latitude": 4.047, "longitude": 9.745, "accuracy_meters": 20},
        "tags": ["shopping", "dining", "business", "architecture"],
    },
    {
        "id": "douala-maritime-museum",
        "city_id": "douala",
        "name": "Maritime Museum",
        "description": "Dedicated to showcasing Cameroon's maritime heritage and naval history through interactive exhibits and historical artifacts.",
        "category": "culture",
        "rating": 4.1,
        "opening_hours": "10:00-17:00",
        "entry_fee": "3000 XAF",
        "location": {"latitude": 4.045, "longitude": 9.750, "accuracy_meters": 10},
        "tags": ["museum", "history", "maritime", "educational"],
    },
    {
        "id": "douala-akwa-palace",
        "city_id": "douala",
        "name": "Akwa Palace",
        "description": "Historic palace representing traditional Douala monarchy and architecture. Important cultural landmark with guided tours available.",
        "category": "culture",
        "rating": 4.4,
        "opening_hours": "09:00-16:00",
        "entry_fee": "5000 XAF",
        "location": {"latitude": 4.041, "longitude": 9.731, "accuracy_meters": 15},
        "tags": ["palace", "history", "monarchy", "guided-tours"],
    },
    {
        "id": "douala-littoral-state-museum",
        "city_id": "douala",
        "name": "Littoral State Museum",
        "description": "Comprehensive museum showcasing regional history, traditional crafts, and contemporary art from the Littoral region.",
        "category": "culture",
        "rating": 4.0,
        "opening_hours": "09:00-17:00",
        "entry_fee": "4000 XAF",
        "location": {"latitude": 4.065, "longitude": 9.755, "accuracy_meters": 12},
        "tags": ["museum", "art", "culture", "history"],
    },
    # Yaounde attractions
    {
        "id": "yaounde-mfoundi-market",
        "city_id": "yaounde",
        "name": "Mfoundi Central Market",
        "description": "Bustling central market with local crafts, textiles, spices, and souvenirs. A vibrant hub of commerce and local culture.",
        "category": "culture",
        "rating": 4.2,
        "opening_hours": "07:00-17:00",
        "entry_fee": "Free",
        "location": {"latitude": 3.848, "longitude": 11.502, "accuracy_meters": 20},
        "tags": ["market", "shopping", "culture", "local"],
    },
    {
        "id": "yaounde-national-museum",
        "city_id": "yaounde",
        "name": "National Museum",
        "description": "Premier museum of Cameroon featuring traditional art, royal regalia, and contemporary exhibitions depicting the nation's cultural diversity.",
        "category": "culture",
        "rating": 4.5,
        "opening_hours": "09:30-16:30",
        "entry_fee": "5000 XAF",
        "location": {"latitude": 3.867, "longitude": 11.525, "accuracy_meters": 15},
        "tags": ["museum", "art", "history", "national-heritage"],
    },
    {
        "id": "yaounde-mount-febe-viewpoint",
        "city_id": "yaounde",
        "name": "Mount Fébé Viewpoint",
        "description": "Elevated viewpoint offering panoramic views of Yaounde city and surrounding hills. Popular spot for photography and picnics.",
        "category": "nature",
        "rating": 4.7,
        "opening_hours": "08:00-19:00",
        "entry_fee": "1000 XAF",
        "location": {"latitude": 3.833, "longitude": 11.498, "accuracy_meters": 20},
        "tags": ["viewpoint", "nature", "photography", "hiking"],
    },
    {
        "id": "yaounde-benedictine-cathedral",
        "city_id": "yaounde",
        "name": "Benedictine Cathedral",
        "description": "Stunning religious and architectural landmark showcasing Neo-Gothic design. Open for visits and worship with guided tours available.",
        "category": "culture",
        "rating": 4.4,
        "opening_hours": "08:00-18:00",
        "entry_fee": "Free",
        "location": {"latitude": 3.850, "longitude": 11.505, "accuracy_meters": 10},
        "tags": ["cathedral", "architecture", "religion", "historical"],
    },
    {
        "id": "yaounde-mvog-betsi-zoo",
        "city_id": "yaounde",
        "name": "Mvog Betsi Zoo",
        "description": "Well-maintained zoo featuring native Cameroonian wildlife and exotic animals. Great for families and nature enthusiasts.",
        "category": "nature",
        "rating": 4.1,
        "opening_hours": "09:00-17:00",
        "entry_fee": "3500 XAF",
        "location": {"latitude": 3.820, "longitude": 11.515, "accuracy_meters": 25},
        "tags": ["zoo", "wildlife", "nature", "family-friendly"],
    },
    {
        "id": "yaounde-chefferie-baffoussam",
        "city_id": "yaounde",
        "name": "Museum of Cameroonian Art",
        "description": "Contemporary art museum showcasing works by Cameroonian artists and international exhibits promoting cultural exchange.",
        "category": "culture",
        "rating": 4.3,
        "opening_hours": "10:00-17:00",
        "entry_fee": "4000 XAF",
        "location": {"latitude": 3.855, "longitude": 11.520, "accuracy_meters": 15},
        "tags": ["museum", "art", "contemporary", "culture"],
    },
    # Buea attractions
    {
        "id": "buea-botanical-garden",
        "city_id": "buea",
        "name": "Buea Botanical Garden",
        "description": "Serene gardens featuring diverse plant species, scenic trails, and panoramic views of Mount Cameroon and the coast.",
        "category": "nature",
        "rating": 4.8,
        "opening_hours": "08:00-17:00",
        "entry_fee": "3000 XAF",
        "location": {"latitude": 4.167, "longitude": 9.283, "accuracy_meters": 20},
        "tags": ["garden", "nature", "hiking", "scenic"],
    },
    {
        "id": "buea-mount-cameroon",
        "city_id": "buea",
        "name": "Mount Cameroon",
        "description": "Africa's highest mountain west of the Congo. Premier trekking destination with breathtaking summit views and diverse ecosystems.",
        "category": "nature",
        "rating": 4.9,
        "opening_hours": "06:00-18:00",
        "entry_fee": "10000 XAF",
        "location": {"latitude": 4.203, "longitude": 9.167, "accuracy_meters": 50},
        "tags": ["mountain", "trekking", "hiking", "adventure", "summit"],
    },
    {
        "id": "buea-colonial-architecture-tour",
        "city_id": "buea",
        "name": "Historic Colonial Buildings",
        "description": "Walking tour of well-preserved German and British colonial architecture including the Governor's Palace and historic mansions.",
        "category": "culture",
        "rating": 4.4,
        "opening_hours": "09:00-16:00",
        "entry_fee": "2500 XAF",
        "location": {"latitude": 4.160, "longitude": 9.240, "accuracy_meters": 25},
        "tags": ["architecture", "history", "colonial", "walking-tour"],
    },
    {
        "id": "buea-museum-buea",
        "city_id": "buea",
        "name": "Museum of Buea",
        "description": "Local history museum documenting Buea's colonial past and the culture of the Cameroon Highlands region.",
        "category": "culture",
        "rating": 4.2,
        "opening_hours": "10:00-16:00",
        "entry_fee": "3000 XAF",
        "location": {"latitude": 4.165, "longitude": 9.245, "accuracy_meters": 10},
        "tags": ["museum", "history", "local-culture", "colonial"],
    },
    {
        "id": "buea-limbe-beach-access",
        "city_id": "buea",
        "name": "Limbe Beach (nearby)",
        "description": "Black sand beach accessible from Buea. Great for swimming, surfing, and enjoying fresh seafood in waterfront restaurants.",
        "category": "nature",
        "rating": 4.5,
        "opening_hours": "08:00-18:00",
        "entry_fee": "Free",
        "location": {"latitude": 4.024, "longitude": 9.129, "accuracy_meters": 30},
        "tags": ["beach", "swimming", "water-sports", "seafood"],
    },
]

notifications: List[Dict[str, Any]] = [
    {
        "id": "notif-1",
        "title": "Departure delay",
        "body": "Yaounde → Douala departure delayed by 15 minutes",
        "created_at": now - timedelta(minutes=10),
        "read": False,
        "category": "travel",
    }
]

sessions: List[Dict[str, Any]] = [
    {
        "session_id": "session-1",
        "device_ip": "203.0.113.45",
        "device_type": "iPhone",
        "device_os": "iOS",
        "session_start": now - timedelta(hours=4),
        "last_activity": now - timedelta(minutes=5),
        "is_active": True,
        "ip_rotation_detected": False,
    }
]
